[package]
name = "evoke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.1"
image = "0.24.4"
vulkano = "0.31.1"
vulkano-shaders = "0.31.1"
vulkano-win = "0.31.0"
winit = "0.27.5"

